# Generated by Django 3.2.4 on 2021-06-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True)),
                ('img', models.ImageField(upload_to='media/articles/images')),
                ('genre', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('date', models.DateTimeField()),
                ('count', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
