# Generated by Django 3.2.4 on 2021-06-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='gallery/')),
                ('slug', models.SlugField(null=True)),
                ('count', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
